---
- name: Add the elasticsearch APT repository key
  apt_key: url=https://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: Add the filebeat APT repository
  apt_repository: repo="deb https://artifacts.elastic.co/packages/{{pl_elasticsearch_major_version}}/apt stable main" state=present

- name: Install filebeat
  apt: name={{item}} state=present force=yes
  with_items:
  - filebeat
  - packetbeat
  - metricbeat
  - heartbeat

- name: Create SSL directory for postfix
  file: path=/etc/pki/tls/certs state=directory

- name: Copy logstash-forwarder.crt
  template: src={{item.src}} dest={{item.dest}}
  with_items:
    - { src: 'logstash_forwarder_crt.j2', dest: '/etc/pki/tls/certs/logstash-forwarder.crt' }
    - { src: 'logstash_forwarder_key.j2', dest: '/etc/pki/tls/certs/logstash-forwarder.key' }

- name: Configure filebeat
  lineinfile: path=/etc/filebeat/filebeat.yml regexp="{{item.regexp}}" line="{{item.replace}}" backup=yes state=present
  with_items:
    - {regexp: '   hosts{{":"}} ["localhost:9200"]', replace: 'hosts{{":"}} ["{{ht_logstash_server_ips_with_port}}"]'}
  notify: restart filebeat
