---
- name: Add the Nginx source to the APT source list
  apt_repository: repo="ppa:nginx/stable" state=present

- name: Install Nginx
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
   - nginx
   - nginx-extras

- name: Configure Nginx
  template: src=nginx.j2 dest=/etc/nginx/nginx.conf
  notify: Restart nginx
