---
- name: Add the OSSEC APT key
  apt_key: url=http://ossec.wazuh.com/repos/apt/conf/ossec-key.gpg.key state=present

- name: Add the OSSEC source to the APT source list
  apt_repository: repo='deb http://ossec.wazuh.com/repos/apt/ubuntu trusty main' state=present

- name: Install OSSEC
  apt: name={{item}} state=present
  with_items:
   - ossec-hids-agent

- name: Configure OSSEC
  template: src=ossec.j2 dest=/var/ossec/etc/ossec.conf
  notify: Restart OSSEC
