---
- name: Adding hadoop user
  user: name=hadoop groups=sudo,shadow shell=/bin/bash append=yes generate_ssh_key=yes ssh_key_file=.ssh/id_rsa

- name: Adding hadoop user to sudoers
  lineinfile: dest=/etc/sudoers state=present regexp='^%hadoop' line='%hadoop ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'

#- name: Download hadoop
#  get_url: url={{hadoop_url}} dest=/opt

- name: Copy hadoop binaries
  copy: src=Softwares/hadoop-2.6.3.tar.gz dest=/opt

- name: Extract hadoop
  unarchive: src=/opt/hadoop-2.6.3.tar.gz dest=/opt copy=no

- name: Set file permissions
  file: path=/opt/hadoop-2.6.3 owner=hadoop group=hadoop recurse=yes
