---
- name: Adding default.json
  template: src=default.json dest=/etc/sensu/conf.d/default.json

- name: restart sensu
  service: name={{item}} state=restarted
  with_items:
  - sensu-server
  - sensu-api
  - uchiwa
