---
- shell: cd /home/{{ansible_ssh_user}} && gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 && curl -sSL https://get.rvm.io | bash -s stable

- shell: source /home/{{ansible_ssh_user}}/.rvm/scripts/rvm
  args:
    executable: /bin/bash

- shell: source /home/{{ansible_ssh_user}}/.basrc
  args:
    executable: /bin/bash

- shell: rvm install 2.1.5

- shell: rvm use 2.1.5 -- default

- shell: gem install bundler

- name: Deploy beef
  git: repo=git://github.com/beefproject/beef.git dest=/home/{{ansible_ssh_user}}/beef accept_hostkey=yes

- name: Run bundler
  bundler: state=present gemfile=/home/{{ansible_ssh_user}}/beef/Gemfile
