#
#About: This must be run on all new servers
#
---
- hosts: '{{inventory}}'
  sudo: yes
  roles:
  - common
  - hostname
  - postfix
  - ntp
  - motd
  - ssh-banner
  - psad
  - rootkit-scanners
  - tiger
