#
#This will update and install only the security updates
#
---
- hosts: '{{inventory}}'
  sudo: yes

  tasks:
  - name: Update cache
    apt: update_cache=yes

  - name: Install security updates
    apt: upgrade=full
