#
#About: This will install sensu-master
#
---
- hosts: '{{inventory}}'
  sudo: yes
  roles:
  - rabbit-mq
  - redis
  - sensu-master
  - sensu-master-checks
  - nginx
  - nginx-sensu-master
  - sensu-client
  - sensu-client-checks
