---
- name: Create ssh folder for www-data
  file: path=/var/www/.ssh state=directory

- name: Create tmp folder
  file: path=/tmp/simple-php-git-deploy/ state=directory mode=0777

- name: Copy ssh key for www-data
  template: src=id_rsa dest=/var/www/.ssh/id_rsa

- name: Copy ssh key for www-data
  template: src=known_hosts dest=/var/www/.ssh/known_hosts

- name: Connect to bitbucket
  shell: sudo -u www-data ssh git@bitbucket.org

- name: Create simple-deploy directory
  file: path=/usr/share/nginx/simple-deploy state=directory

- name: Copy simple-deploy script
  template: src=deploy.j2 dest=/usr/share/nginx/simple-deploy/deploy.php

- name: Copy simple-deploy script
  template: src=deploy_conf.j2 dest=/usr/share/nginx/simple-deploy/deploy-config.php

- name: Stop Nginx
  service: name=nginx state=stopped

- name: Configure Nginx virtualhost for simple-deploy
  template: src=simple_deploy.j2 dest=/etc/nginx/sites-available/simple-deploy

- name: Configure Nginx virtualhost for simple-deploy
  template: src=simple_deploy.j2 dest=/etc/nginx/sites-enabled/simple-deploy

- name: Start Nginx
  service: name=nginx state=started
