---
- name: Launch ec2
  ec2:
    key_name: "{{ec2_key}}"
    instance_type: "{{instance_type}}"
    image: "{{ami}}"
    group: "{{sg_group}}"
    wait: yes
    wait_timeout: 500
    count: 1
    monitoring: yes
    vpc_subnet_id: "{{vpc_subnet}}"
    assign_public_ip: yes
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    region: "{{aws_region}}"
