---
- name: Adding Cassandra repo
  apt_repository: repo='deb http://www.apache.org/dist/cassandra/debian 22x main' state=present

#- name: Add the Cassandra APT key
#  apt_key: keyserver=pgp.mit.edu id={{item}} state=present
#  with_items:
#  - F758CE318D77295D
#  - 2B5C1B00
#  - 0353B12C

- name: Add the Cassandra APT key
  apt_key: keyserver=pgp.mit.edu id=F758CE318D77295D state=present

- name: Add the Cassandra APT key
  apt_key: keyserver=pgp.mit.edu id=2B5C1B00 state=present

- name: Add the Cassandra APT key
  apt_key: keyserver=pgp.mit.edu id=0353B12C state=present

- name: Install Cassandra
  apt: name={{item}} state=latest update_cache=yes
  with_items:
   - cassandra
