---
- name: Download oauth
  get_url: url=https://github.com/bitly/oauth2_proxy/releases/download/v2.0.1/oauth2_proxy-2.0.1.linux-amd64.go1.4.2.tar.gz dest=/etc/nginx

- name: Extract oauth
  unarchive: src=/etc/nginx/oauth2_proxy-2.0.1.linux-amd64.go1.4.2.tar.gz dest=/etc/nginx copy=no

- name: Stop Nginx
  service: name=nginx state=stopped

- name: Configure virtual host for Jenkins
  template: src=virtualhost_jenkins.j2 dest=/etc/nginx/sites-available/default

- name: Configure Nginx virtualhost
  template: src=virtualhost_jenkins.j2 dest=/etc/nginx/sites-enabled/default

- name: Configure Nginx virtualhost with SSL
  template: src=virtualhost_ssl_jenkins.j2 dest=/etc/nginx/sites-available/default-ssl

- name: Configure Nginx virtualhost with SSL
  template: src=virtualhost_ssl_jenkins.j2 dest=/etc/nginx/sites-enabled/default-ssl

- name: Start Nginx
  service: name=nginx state=started
