---
- name: Create Jenkins directory
  file: path=/home/jenkins/cli state=directory

- name: Download Jenkins CLI
  get_url: url=http://localhost:8080/jnlpJars/jenkins-cli.jar dest=/home/jenkins/cli/jenkins-cli.jar

- name: Copy install jenkins plugins shell script
  template: src=install-jenkins-plugin.sh.j2 dest=/home/jenkins/install-jenkins-plugins.sh

- name: Install jenkins plugins
  shell: sh /home/jenkins/install-jenkins-plugins.sh {{item}}
  with_items:
  - git
  - s3
  - email-ext
  - rebuild
  - thinBackup
  - performance
  - postbuild-task

- name: Stop Jenkins
  service: name=jenkins state=stopped

- name: Start Jenkins
  service: name=jenkins state=started
