---
- name: Create Jenkins directory
  file: path=/home/jenkins/cli state=directory

- name: Download Jenkins CLI
  get_url: url=http://localhost:8080/jnlpJars/jenkins-cli.jar dest=/home/jenkins/cli/jenkins-cli.jar

- name: Install Git plugin
  shell: java -jar /home/jenkins/cli/jenkins-cli.jar -s http://localhost:8080/ install-plugin git -deploy
  ignore_errors: True

- name: Install categorized-view plugin
  shell: java -jar /home/jenkins/cli/jenkins-cli.jar -s http://localhost:8080/ install-plugin categorized-view -deploy
  ignore_errors: True

- name: Stop Jenkins
  service: name=jenkins state=stopped

- name: Start Jenkins
  service: name=jenkins state=started
