---
- name: Adding Jenkins user
  user: name=jenkins groups=sudo,shadow shell=/bin/bash append=yes generate_ssh_key=yes ssh_key_file=.ssh/id_rsa

- name: Adding Jenkins user to sudoers
  shell: sudo echo "jenkins ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers
  changed_when: False

- name: Add the Jenkins APT repository key
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present

- name: Add the Jenkins APT repository
  apt_repository: repo="deb http://pkg.jenkins-ci.org/debian binary/" state=present

- name: Install Jenkins
  apt: name={{item}} state=present update_cache=yes
  with_items:
  - jenkins

- name: Create Jenkins directory
  file: path=/home/jenkins/cli state=directory

- name: Download Jenkins CLI
  get_url: url=http://localhost:8080/jnlpJars/jenkins-cli.jar dest=/home/jenkins/cli/jenkins-cli.jar

- name: Install Git plugin
  shell: java -jar /home/jenkins/cli/jenkins-cli.jar -s http://localhost:8080/ install-plugin git -deploy

- name: Install categorized-view plugin
  shell: java -jar /home/jenkins/cli/jenkins-cli.jar -s http://localhost:8080/ install-plugin categorized-view -deploy

- name: Restart Jenkins
  shell: java -jar /home/jenkins/cli/jenkins-cli.jar -s http://localhost:8080 safe-restart
