---
- name: Adding Jenkins user
  user: name=jenkins groups=sudo,shadow shell=/bin/bash append=yes generate_ssh_key=yes ssh_key_file=.ssh/id_rsa

- name: Adding Jenkins user to sudoers
  shell: sudo echo "jenkins ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers
  changed_when: False

- name: Set JAVA_HOME
  shell: sudo echo "export JAVA_HOME=/usr/lib/jvm/java-8-oracle" >> /home/jenkins/.bashrc

- name: Add the Jenkins APT repository key
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present

- name: Add the Jenkins APT repository
  apt_repository: repo="deb http://pkg.jenkins-ci.org/debian binary/" state=present

- name: Install Jenkins
  apt: name={{item}} state=present update_cache=yes
  with_items:
  - jenkins

- name: Configure Jenkins
  template: src=jenkins.j2 dest=/etc/default/jenkins
