---
- name: Add bitcoin APT repository
  apt_repository: repo="ppa:bitcoin/bitcoin" state=present

- name: Install bitcoin
  apt: name={{item}} state=present force=yes
  with_items:
  - bitcoin-qt
  - bitcoind
  - bfgminer
  
- name: Adding bitcoin user
  user: name=bitcoin groups=sudo,shadow shell=/bin/bash append=yes generate_ssh_key=yes ssh_key_file=.ssh/id_rsa

- name: Adding bitcoin user to sudoers
  shell: sudo echo "bitcoin ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers
  changed_when: False

- name: Create bitcoin directory
  file: path=/home/bitcoin/.bitcoin state=directory

- name: Configure bitcoin
  template: src=bitcoin.j2 dest=/home/bitcoin/.bitcoin/bitcoin.conf

#- name: Deploy
#  git: repo=git://github.com/luke-jr/bfgminer.git dest=/home/bitcoin/bfgminer accept_hostkey=yes
