---
- name: Add the php7 source to the APT source list
  apt_repository: repo="ppa:ondrej/php-7.0" state=present
  tags:
    - php7-installation

- name: Install Php7
  apt: name={{item}} state=present
  with_items:
   - php7.0-common
   - libapache2-mod-php7.0
   - php7.0-cgi
   - php7.0-cli
   - php7.0-phpdbg
   - php7.0-fpm
   - libphp7.0-embed
   - php7.0-dev
   - php7.0-dbg
   - php7.0-curl
   - php7.0-enchant
   - php7.0-gd
   - php7.0-gmp
   - php7.0-imap
   - php7.0-interbase
   - php7.0-intl
   - php7.0-ldap
   - php7.0-mcrypt
   - php7.0-readline
   - php7.0-odbc
   - php7.0-pgsql
   - php7.0-pspell
   - php7.0-recode
   - php7.0-snmp
   - php7.0-tidy
   - php7.0-xmlrpc
   - php7.0-xsl
   - php7.0
   - php7.0-json
   - php-all-dev
   - php7.0-sybase
   - php7.0-sqlite3
   - php7.0-mysql
   - php7.0-opcache
   - php7.0-bz2
  tags:
    - php7-installation

- name: Configure Php
  template: src=php.ini dest=/etc/php/7.0/fpm/php.ini
  notify: Restart Php
  tags:
    - php7-configuration
