---
- name: Add New Relic APT key
  apt_key: url=https://download.newrelic.com/548C16BF.gpg state=present

- name: Add New Relic repo
  apt_repository: repo="deb http://apt.newrelic.com/debian/ newrelic non-free" state=present

- name: Install New Relic agent
  apt: name={{item}} state=present
  with_items:
  - newrelic-sysmond

- name: Configure New Relic agent
  template: src=new_relic.j2 dest=/etc/newrelic/nrsysmond.cfg
  notify: Restart newrelic-sysmond

- name: Run new relic install-tiger
  shell: sudo newrelic-install install
