---
- name: Install Php
  apt: name={{item}} state=present
  with_items:
   - php5
   - php5-cli
   - php5-fpm
   - php5-mysql
   - php5-curl
   - php5-gd
   - php5-intl
   - php-pear
   - php5-imagick
   - php5-imap
   - php5-mcrypt
   - php5-memcache
   - php5-ming
   - php5-ps
   - php5-pspell
   - php5-recode
   - php5-snmp
   - php5-sqlite
   - php5-tidy
   - php5-xmlrpc
   - php5-xsl
   - php5-memcached
   - php-apc
   - memcached
   - mcrypt
   - newrelic-php5

- name: Configure Php
  template: src=php.ini dest=/etc/php5/fpm/php.ini
  notify: Restart Php

- name: Setup newrelic application-name
  shell: sudo echo newrelic-php5 newrelic-php5/application-name string "PHP Application" | debconf-set-selections
  notify: Restart Php

- name: Setup newrelic license-key
  shell: sudo echo newrelic-php5 newrelic-php5/license-key string "{{new_relic_license_key}}" | debconf-set-selections
  notify: Restart Php

- name: Restart newrelic
  server: name=newrelic-sysmond state=restarted
