---
- name: Gather ec2 facts
  ec2_facts:
  when: dc_env == "aws"

- name: Stop ec2 instance
  local_action:
    module: ec2
    instance_ids: "{{ansible_ec2_instance_id}}"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    region: "{{ansible_ec2_placement_region}}"
    state: stopped
  when: dc_env == "aws"
