---
- name: Create build directory
  file: path='{{pl_docker_packer_build_dir}}' state=directory

- name: Copy template file to build
  template: src='{{pl_docker_template}}.json.j2' dest='{{pl_docker_packer_build_dir}}/{{pl_docker_template}}.json'

- name: Build docker image
  shell : packer build '{{pl_docker_template}}.json'
  args:
    chdir: '{{pl_docker_packer_build_dir}}'

- name: Docker repo login
  shell: docker login '{{pl_docker_repo_url}}' --username '{{pl_docker_repo_username}}' --password '{{pl_docker_repo_password}}'

- name: Push image
  shell: docker push '{{pl_docker_repo_url}}/{{pl_docker_repo_username}}/{{pl_docker_repo_name}}/{{pl_docker_template}}:{{pl_tag}}'

- name: Docker repo logout
  shell: docker logout '{{pl_docker_repo_url}}'
