---
- name: Adding banner info in sshd.conf
  lineinfile: dest=/etc/ssh/sshd_config regexp='#Banner /etc/issue.net' line="Banner /etc/issue.net"
  tags:
    - ssh-banner-configuration

- name: Update ssh banner
  template: src=ssh-banner.j2 dest=/etc/issue.net
  tags:
    - ssh-banner-configuration

- name: Change StrictHostKeyChecking to no
  lineinfile: dest=/etc/ssh/ssh_config regexp='#   StrictHostKeyChecking' line="    StrictHostKeyChecking no"
  tags:
    - ssh-strict-key-configuration

- name: Restart ssh
  service: name=ssh state=restarted
