---
- name: Add the playdeb APT key
  apt_key: url=http://archive.getdeb.net/getdeb-archive.key state=present

- name: Add playdeb repository
  apt_repository: repo="deb http://archive.getdeb.net/ubuntu trusty-getdeb games" state=present

- name: Update cache
  apt: update_cache=yes
